language: shell # minimal

os:
  - linux

dist: bionic

branches:
  only:
    - master
    - development

services:
  - docker

before_install:
  - |
    docker image build \
      -f Test.Dockerfile \
      -t juliocesarmidia/simple-app-test:latest .

script:
  - |
    docker container run --rm \
    --name simple-app-test \
    juliocesarmidia/simple-app-test:latest
