sudo: required
services:
  - docker

before_install:
  - docker image build -f Dockerfile-test -t juliocesarmidia/app-login-test .

script:
  - docker container run --name app-login-test juliocesarmidia/app-login-test