version: '3'
services:
  db:
    container_name: db
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_cookie_project
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    # volumes:
      # - mysql-db:/var/lib/mysql
      # - ./queries.sql:/docker-entrypoint-initdb.d/data.sql
      
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: db_cookie_project
      DB_USER: root
      DB_PASSWORD: admin
    links:
     - db
    healthcheck:
      test: ["CMD", "nc -lk db 3306"]
      interval: 30s
      timeout: 1s
      retries: 1

  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: Dockerfile-migrations
      args:
        - DB_HOST=db
        - DB_DATABASE=db_cookie_project
        - DB_USER=root
        - DB_PASSWORD=admin
    restart: "no"
    depends_on:
      - db
    volumes:
      - /migrations/node_modules
      - ./migrations:/migrations
    links:
     - db

  test:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile-test
    restart: "no"

# volumes:
#   mysql-db:
