FROM juliocesarmidia/node_base:v9.10
LABEL maintainer="julio@blackdevs.com.br"

WORKDIR /migrations/
COPY ./migrations/ /migrations/

RUN npm install
RUN chmod +x /migrations/run.sh

ENTRYPOINT [ "/bin/bash", "-x", "/migrations/run.sh"]

# Build this image
# docker image build -f Dockerfile-migrations -t migrations .

# Run this image
# docker container run --name migrations migrations
# docker container run -it --name migrations migrations bashapp-

# docker-compose run migrations bash