version: '3.4'

services:
  db:
    container_name: db
    image: mysql:8.0
    ports:
      - '0.0.0.0:3306:3306'
    restart: "on-failure"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-admin}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db_cookie_project}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
      MYSQL_ROOT_HOST: "%"
    networks:
      - simpleapp
    volumes:
      - mysql-db:/var/lib/mysql

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:80
    restart: "on-failure"
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-db}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db_cookie_project}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
    networks:
      - simpleapp
    volumes:
      - ./:/var/www/html/
      - ./000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    healthcheck:
      test: ["CMD", "curl", "-Iv", "http://app"]
      interval: 30s
      timeout: 1s
      retries: 1

  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: Migrations.Dockerfile
    restart: "no"
    depends_on:
      - db
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-db}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-db_cookie_project}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
    volumes:
      - /migrations/node_modules
      - ./migrations:/migrations
    networks:
      - simpleapp

volumes:
  mysql-db:

networks:
  simpleapp:
    driver: bridge
