FROM juliocesarmidia/ubuntu_base:v18.04
LABEL maintainer="julio@blackdevs.com.br"

RUN apt-get install -y -qq mysql-client

ARG DB_HOST
ARG DB_DATABASE
ARG DB_USER
ARG DB_PASSWORD

# ENV DB_HOST=${DB_HOST}
# ENV DB_DATABASE=${DB_DATABASE}
# ENV DB_USER=${DB_USER}
# ENV DB_PASSWORD=${DB_PASSWORD}

COPY ./migrations/ /migrations/

WORKDIR /migrations/
RUN cd /migrations/
RUN curl -sL https://deb.nodesource.com/setup_9.x | apt-get install -y -qq nodejs \
  && apt-get install -y -qq npm \
  && apt-get update -qq

RUN npm install
RUN chmod +x /migrations/run.sh

# ENTRYPOINT [ "/bin/bash", "-x", "/migrations/run.sh", "$DB_USER", "$DB_PASSWORD", "$DB_HOST", "$DB_DATABASE" ]
ENTRYPOINT [ "/bin/bash", "-x", "/migrations/run.sh", "root", "admin", "db", "db_cookie_project"]

# Build this image
# docker image build -f Dockerfile-migrations -t migrations .

# Run this image
# docker container run --name migrations migrations
# docker container run -it --name migrations migrations bashapp-

# docker-compose run migrations bash