FROM juliocesarmidia/node_base:v9.10
LABEL maintainer="julio@blackdevs.com.br"

WORKDIR /migrations/
COPY ./migrations/ /migrations/

RUN npm install --silent
RUN chmod +x /migrations/docker-entrypoint.sh

ENTRYPOINT [ "/bin/bash", "-x", "/migrations/docker-entrypoint.sh"]

CMD [ "npm", "run", "start" ]

# Build this image
# docker image build -f Dockerfile-migrations -t migrations .

# Run this image
# docker container run --name migrations migrations
# docker container run -it --name migrations migrations bashapp-
