FROM juliocesarmidia/apache_php_base:v18.04
LABEL maintainer="julio@blackdevs.com.br"

WORKDIR /var/www/html/
COPY . /var/www/html/

RUN composer install

CMD ["./vendor/bin/phpunit", "--bootstrap", "vendor/autoload.php", "--testdox", "tests/"]

# Build this image
# docker image build -f Dockerfile-test -t test .

# Run this image
# docker container run --name test test
# docker container run -it --name test test bash