version: '3'
services:
  db:
    container_name: db
    image: mysql:5.7.22
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-admin}
      MYSQL_DATABASE: ${DB_DATABASE:-db_cookie_project}
      MYSQL_USER: ${DB_USER:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-admin}
    networks:
      - netlocal
    # volumes:
      # - mysql-db:/var/lib/mysql
      # - ./queries.sql:/docker-entrypoint-initdb.d/data.sql

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_DATABASE: ${DB_DATABASE:-db_cookie_project}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
    links:
      - db
    networks:
      - netlocal
    healthcheck:
      test: ["CMD", "nc -lk db 80"]
      interval: 30s
      timeout: 1s
      retries: 1

  migrations:
    container_name: migrations
    build:
      context: .
      dockerfile: Dockerfile-migrations
    restart: "no"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_DATABASE: ${DB_DATABASE:-db_cookie_project}
      DB_USER: ${DB_USER:-root}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
    volumes:
      - /migrations/node_modules
      - ./migrations:/migrations
    links:
      - db
    networks:
      - netlocal

  test:
    container_name: test
    build:
      context: .
      dockerfile: Dockerfile-test
    restart: "no"
    networks:
      - netlocal

# volumes:
#   mysql-db:

networks:
  netlocal:
    driver: bridge