#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# run tests of this branch
./vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox tests/$BRANCH_NAME/

if [ $? -ne 0 ]; then
  exit 1
fi
