#!/bin/sh

BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

# run tests of this branch
# test -f ./vendor/bin/phpunit && ./vendor/bin/phpunit --bootstrap vendor/autoload.php --testdox tests/$BRANCH_NAME/
test -f ./vendor/bin/phpunit && ./vendor/bin/phpunit

if [ $? -ne 0 ]; then
  exit 1
fi
